### PR TITLE
move libs_gcn under libs folder

### PR DESCRIPTION
**Pull request by skojaku**
# Proposal 
- Move "libs_gcn" under "libs" folder 

More commits to come:

### CODE REVIEW

**Comment by skojaku** [comment]
The base embedding is not used as the initial embedding for DeepVAGE. It's nice if we don't need it. 

https://github.com/ashutosh1919/persona2vec_gcn/blob/8446205c73a0a3aab11a10324089e563c8876aae/libs/persona2vec_gcn/persona2vec_gcn/model.py#L75

**Comment by skojaku** [comment]
@ashutosh1919 
https://github.com/ashutosh1919/persona2vec_gcn/blob/b3c85da0365995cda6c50b7a50e13d8b28d8f7a1/libs/persona2vec_gcn/persona2vec_gcn/vgae.py#L157

I guess this part generates a dense NxX adjacency matrix as the input node features. This is a very big feature matrix so that the computational cost would be very huge. I wonder if we can substitute it with a more smaller feature matrix like the eigenvectors of the Laplacian matrix.

**Comment by ashutosh1919** [comment]
@skojaku Thanks for review. I will move stuff inside `libs`.

Also, I tried by taking features as different size eigen. vectors of graph Laplacian matrix but it doesn't perform good. For example, if base embedding ROC for model is 64% then it produces the persona embedding (with eigen vectors as features) ROC 66% whereas persona embedding with adjacency row as feature has ROC of 78%.

**Comment by skojaku** [comment]
Interesting. i guess this might be something to do with the persona graph. laplacian eigen vectors capture communities in networks. in a persona graph, we artifocially create personas but they are similar to communities because they are weakly connected. consequently, the persana overshadow organic communities.

**Comment by skojaku** [comment]
did you compute the laplacian with the original graph or the persona graph？

**Pull request merged**
